# Generated by Django 3.0.6 on 2021-07-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=13)),
                ('email', models.EmailField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
