# Generated by Django 3.0.6 on 2021-07-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hire',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('msg', models.TextField()),
            ],
        ),
    ]
